# Use an official Node runtime as a parent image
FROM node:latest

# Set the working directory in the container
WORKDIR /geminiApp

# Copy all files to the container
COPY . .

# Install backend dependencies
RUN npm install -g @google/generative-ai
RUN cd api && npm install
RUN cd client/client-app && npm install

# Build the client app
RUN cd client/client-app && npm run build

# Expose the port the API is reachable on
EXPOSE 4000
EXPOSE 3000

# Start both the API and the client app using a script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
CMD ["sh" , "./entrypoint.sh"]
