name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile.dev
        push: true
        tags: cheekyff/geminiproject:latest

    - name: Run server
      run: |
        docker run -d --name geminiapp -p 4000:4000 -p 3000:3000 cheekyff/geminiproject:latest
        sleep 15  # Wait for the server to start

    - name: Verify the server is running
      run: |
        curl -f http://localhost:3000
    
    - name: Stop the server
      if: always()
      run: docker stop geminiapp
